### ISSUE TITLE
iOS port

### ISSUE THREAD

**Issue by EstebanMonge** [andresth/Kandroid#14]
Hello, we are very interested in get a port to iOS, how can contact you?

**Comment by andresth** [comment]
Hi,
you can contact me via iosrequest@andres.in on this matter.
But if you want to ask me to port Kandroid to iOS, then I have to disappoint you.
I am developing Kandroid in my spare time, which is somewhat limited.
Also I don't have any experience with the iOS platform and currently do not plan to invest any time to change that.

But feel free to try and port it your self. You can contact me if you have any questions.
