### ISSUE TITLE
Login fails with Kanboard master branch

### ISSUE THREAD

**Issue by andresth** [andresth/Kandroid#15]
The version code `master` is not handled properly.

**Comment by 2Belette** [comment]
Thanks for this fix as I am on the same situation..
Any idea when the fix would be available in F-Droid? (I have 0.5.3 now, fix is not included)

**Comment by andresth** [comment]
I just pushed a new release to github. F-Droid should find it on their next update run.

**Comment by 2Belette** [comment]
many thanks! Do you know F-Droid run frequency ? once per day/week? (I don't see the update on the store)

**Comment by andresth** [comment]
I just saw that the new version si available on f-droid
