### ISSUE TITLE
Crash if project description is empty

### ISSUE THREAD

**Issue by EstebanMonge** [andresth/Kandroid#2]
**Please, do not create duplicate issues**

### Actual behaviour

Kandroid stop works when logged in Kanboard.

### Expected behaviour

Just see the tasks!

### Steps to reproduce
I installed 0.4 and 0.4.1 but Kandroid crash on start, I can uninstall the application, configure the url but when Kandroid makes the loggin the application has a unexpected close. 

### Configuration

- Kandroid version: 0.4.1
- Android/Mod version: Android 6.0, EMUI 4.0
- Theme (if you use one): Spectrum
- Device type, name and manufacturer: Huawei Mate 8
- Kanboard version: 1.0.38

**Comment by andresth** [comment]
Can you send me the logcat output of the crash?

With the Android SDK installed you need to run this command and send me the output.
`adb logcat Kandroid:d *:e`

If you have root on your phone, you can also use an app like aLogcat.

**Comment by andresth** [comment]
Version 0.4.2 has the option to send a crash report via email.  
Please use this version to send me more details.

**Comment by EstebanMonge** [comment]
I tested and I can confirm that is fixed
