### ISSUE TITLE
HTTPS login error java.security.certPath

### ISSUE THREAD

**Issue by Larnal** [andresth/Kandroid#23]
### Actual behaviour

When I try to login to my kanboard server, A black box appears telling me this error : 

> Failed to establish encrypted connection.
> Reason: java.security.certPath ValidatorException: Trust anchor for certification path not found.

My certificate is provided by Let's Encrypt and my server is a Raspberry pi 2 with raspbian (Debian 8 based) running nginx 1.9.2. Connection from web browser works perfectly.

### Expected behaviour

The app should log in to my kanboard server

### Steps to reproduce

1. Enter server address starting with https://
2. Enter my creditentials
3. Press the SIGN IN Button

### Configuration

- Kandroid version: 0.5.4
- Android/Mod version: 7.1.2
- Theme (if you use one): 
- Device type, name and manufacturer: LG G4
- Kanboard version: 1.0.44

**Comment by Larnal** [comment]
Problem solved.

It was my Nginx server configuration with SSL certificate that caused the problem. I used cert.pem for the certificate instead of fullchain.pem.

**Comment by dg10a** [comment]
I'm seeing this issue as well. The site is accessible using a web browser.
