### ISSUE TITLE
Unknown host from framaboard.org

### ISSUE THREAD

**Issue by valentin-blank** [andresth/Kandroid#24]
Hi,

Kandroid tells me "Unknowed host" when attempting to login. 

I am using https on my kanboard, and it is hosted on framaboard.org

So the url I use is like this one : "https://user.framaboard.org"

- Kandroid version: 0.5.4
- Android/Mod version: Android 6.0.1 with
Cyanogenmod 13.0-20161015-NIGHTLY-m7

- Device type, name and manufacturer: HTC ONE m7

- Kanboard version: 1.0.40
with these plugins :
 Github Webhook 1.0.4
 RocketChat 1.0.5
 Github Issues Frontend 1.0.1
 Mattermost 1.0.4
 Self-Registration 1.0.6
 Slack 1.0.6
 Gitlab Webhook 1.0.5

**Comment by valentin-blank** [comment]
Not working either with just "https://framaboard.org" as URL to Kanboard server.

This time it doesn't do anything, the sign in screen just loop to itself.

Hope this help.

**Comment by marienfressinaud** [comment]
It seems to be a problem on Framaboard side, you can follow the discussion on https://framacolibri.org/t/impossibilite-dutiliser-kandroid-avec-framaboard/1732/

I'll try to investigate more on the problem when I'll have time. I think it's safe to close this ticket which looks like duplication of #22 (not related to Framaboard instance I think)

**Comment by marienfressinaud** [comment]
Hi @valentin-blank, problem is solved on Framaboard instance :)

**Comment by andresth** [comment]
Hi @marienfressinaud ,

thanks for your help
