### ISSUE TITLE
Support of movement of task to column

### ISSUE THREAD

**Issue by mariovor** [andresth/Kandroid#25]
### Actual behaviour
Cannot move task to different column from task view.

### Expected behaviour

Should be able to move move to different column.

### Configuration

- Kandroid version: v0.5.4 (from f-droid store)
- Android/Mod version: 7.1.2 / Lineage fork
- Theme (if you use one): -
- Device type, name and manufacturer: Oneplus 3T
- Kanboard version: 1.0.45

**Comment by andresth** [comment]
Supported in v0.5.6
