### ISSUE TITLE
Can't sign in on my yunohost instance of kanboard

### ISSUE THREAD

**Issue by b-allard** [andresth/Kandroid#27]
### Actual behaviour

Hi, I tried to connect on my Kanboard instance (on an Yunohost install). When i tried to connect on it nothing append (even an popup error). Just a loader and i came back on the sigin in screen.

###Debug info : 
When i see the log on android studio, i see an html response that represent the login screen of my yunohost instance

When i tried with postman on basic authentification, i see my kanboard dashboard.

### Configuration

- Kandroid version:  v0.5.6
- Android/Mod version: android 7
- Theme (if you use one): /
- Device type, name and manufacturer: sony
- Kanboard version: 1.0.41

Thanks in advance for the help,

Benjamin

**Comment by andresth** [comment]
Hi,
did you by chance `index.php` in the server URL? This would explain the behaviour.

You don't need to include any file in your URL, it should look like this `https://kanboard.example.com`

BTW the next version will show an error message for this case.

**Comment by blutux** [comment]
Nope, my adress is something like https://mydomaine.net/kanboard/

**Comment by andresth** [comment]
Could you please try if it works when you add `jsonrpc.php` to the URL?

**Comment by blutux** [comment]
it doesn't work :/ and i have the same error, as if the user and the password wasn't pass when i tried to authenticate me

**Comment by andresth** [comment]
Hi,

I finally found the time to setup yunohost for testing and I think has to do something with the Single Sign On mechanism used by yunohost.

It works only when you define Kanbord as a public site in the installation process

![grafik](https://user-images.githubusercontent.com/23014287/29676292-f16594d2-88f7-11e7-9d4b-c7fd5b316c32.png)

I don't know how to change a yunohost app to public after installation. But if you decide to reinstall it, you should definitely make a backup of your database, bacause **all data will be lost when you delete it**.
