### ISSUE TITLE
Code 500 Server Error

### ISSUE THREAD

**Issue by aljawaid** [andresth/Kandroid#28]
### Actual behaviour
Sign in successfully, while retrieving kanboard data it is just a spinning circle then eventually error `500 Internal Server Error` `HTTP response 500`
Can't use the app at all.  I'm on a self-cert ssl but it worked before on both phones, now both phones do not work with the app.

### Configuration

- Kandroid version: 0.5.6
- Theme (if you use one): Tried on Default and also KanboardCSS
- Device type, name and manufacturer: BlackBerry Android and Samsung S5
- Kanboard version: 1.0.45

**Comment by aljawaid** [comment]
same on 0.5.7 too...seems to sign in, but just non stop spinning circles and the finally code 50 error 500

**Comment by andresth** [comment]
Hi,
this message means that something went wrong at your server.
The logfiles on your server should provide more information.

**Comment by aljawaid** [comment]
`92.22.XXX.251 - - [17/Aug/2017:10:59:43 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 401 73 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:43 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 401 73 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:43 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 401 73 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:43 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 401 73 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:43 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 401 73 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:43 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 401 73 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:44 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 200 36 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:44 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 200 605 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:44 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 500 - "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:44 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 200 14945 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:44 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 200 1289 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"
92.22.XXX.251 - - [17/Aug/2017:10:59:44 +0100] "POST /planner/jsonrpc.php HTTP/1.1" 200 342243 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; STV100-4 Build/MMB29M)"`

Does that make any sense?

* My kanboard is installed as `domain.co.uk/planner`

**Comment by aljawaid** [comment]
ping @andresth

**Comment by andresth** [comment]
Hi,

your `access.log` shows some 401 (Authentication Error) and one 500 (General Server Error) status codes.

I think the `error.log` should provide more information on these.

**Comment by gdinit** [comment]
hi. Thanks for developing an android app. Same issue here. On mobile now but can provide details later.

**Comment by aljawaid** [comment]
@andresth no information in my server error log files. Just tried and checked again.  Just get a `Code 50` error on Kandroid and the spinner stays spinning so just close the app as it becomes useless without login.  Reinstalled on both mobiles too.

**Comment by aljawaid** [comment]
**Finally this got solved**

My server uses cPanel self-sign ssl and this seemed to be blocking the Kandroid app.

Setting the below in **`config.php`** solved it for me.

```// Set to false to allow self-signed certificates
define('HTTP_VERIFY_SSL_CERTIFICATE', false);
```

Hope it helps others.
