### ISSUE TITLE
Not possible to create tasks or see projects without tasks

### ISSUE THREAD

**Issue by rednaxela-work** [andresth/Kandroid#30]
### Actual behaviour

Installed latest Kanboard version 1.0.46 just today, also current Android version 0.5.7 (on Android 7.1.2 [ LineageOS 14.1]). Both for the first time. 
I have the default admin user and created a second "normal" user. 
I created three projects, with only one of them having two tasks. The other two are empty. 
For the sake of comfort I assigned the role "Project Manager" to the normal user for my three projects. 

Now in Kandroid I login with the normal user 's credentials but I can only see the one project with the two tasks. And I'm not able to create new tasks. 
The screenshots of the app suggest that this would be possible. Am I wrong? 
Is it also expected behavior that I can only see "filled" projects? If I can't create tasks on the client, it may make sense. 
Thanks, Alex

**Comment by andresth** [comment]
Hi,

empty project are currently not visible in the Dashboard.

If you swipe in from the left corner of your device (or tab the three stripes on the top left corner) it will open a menu where you can access all your projects.

**Comment by rednaxela-work** [comment]
Hey and thanks for the reply!

But I can't see the described functionality in my app, see my screenshot of the opened side menu:
![screenshot_20170824-115207](https://user-images.githubusercontent.com/3063323/29660982-06b36e84-88c3-11e7-999c-f8816bbb729f.png)

I don't see any way to access the third project that doesn't yet have a single task.

Point 2:
Also I'm still puzzled about the (+) button on the screenshots in the readme.md.

It made me think that one could create tasks in your app, but either that was a misunderstanding on my side or it's a bug. I can't create tasks.
