### ISSUE TITLE
F-droid inclusion of Kandroid?

### ISSUE THREAD

**Issue by Jibec** [andresth/Kandroid#4]
Hi, I wanted to ask the Fdroid team to package Kandroid so I can get it on my phone.

The request form says: 
* [ ] The original app author has been notified (and supports the inclusion).

Do you support this inclusion?

Ideally, you may take the lead for this inclusion. By creating the ticket or pushing required metadata https://f-droid.org/wiki/page/Inclusion_How-To

thanks for your help

**Comment by aljawaid** [comment]
Hello, as a workaround, you could try to download the apk file from here and then transfer it to your phone and open it?  That's how I did it and my Android opened and installed it without a problem.

**Comment by andresth** [comment]
Hi @Jibec 
I think this is a good idea.
I will create the ticket within the next few days.

**Comment by Jibec** [comment]
I'm glad you like the idea.
I have to be honest, your build doesn't work on my fairphone, and I don't like the idea of installing apk directly from unknown source and hoped using f-droid would improve situation ;).

I have fairphone FP1, without google tools, with android 4.2.2 and kernel 3.4.5
It just don't run the apk and say something went wrong.

**Comment by andresth** [comment]
I have to disappoint you. You need Android 5 or higher to run the app.

Anyhow, my [submission request](https://gitlab.com/fdroid/rfp/issues/69) was accepted.

**Comment by Jibec** [comment]
Le 14 mars 2017 23:09:44 UTC+01:00, Thomas Andres <notifications@github.com> a écrit :
>I have to disappoint you. You need Android 5 or higher to run the app.
>
>Anyhow, my [submission
>request](https://gitlab.com/fdroid/rfp/issues/69) was accepted.

Well, I'm not close to change my smartphone ;) is the framework gap big from 4 to 5? I would understand if you don't support Android 4, but I wish to understand (it is not obvious to end user).
-- 
Jean-Baptiste Holcroft

**Comment by andresth** [comment]
Actually there was no technical reason, I choose Android 5 when I started the project.
I think it should also compile for an earlier Android version, I think I will test it in an AVD soon.

**Comment by Jibec** [comment]
Le 14/03/2017 à 23:35, Thomas Andres a écrit :
> Actually there was no technical reason, I choose Android 5 when I
> started the project.
> I think it should also compile for an earlier Android version, I think I
> will test it in an AVD soon.

I don't know what is "AVD", but I understand you'll have a look. Would
you like me to create a new issue related to this subject?
In the meanwhile, thanks for the froid integration, I think we can we
close this issue, isn't it?
-- 
Jean-Baptiste Holcroft

**Comment by andresth** [comment]
I just created a new issue for this.
