### ISSUE TITLE
App version in f-droid is outdated

### ISSUE THREAD

**Issue by rEnr3n** [andresth/Kandroid#46]
**Please, do not create duplicate issues**

### Actual behaviour

The latest version of the app in f-droid is 0.5.7.

### Expected behaviour

The version should be 0.5.8 as of this writing.

### Steps to reproduce

1. Visit this page  https://f-droid.org/packages/in.andres.kandroid/
1. Check the version

**Comment by ianme** [comment]
Please @andresth this is important! Currently this great app is useless in F-Droid (0.5.7) due to the version check bug. Thanks for your work.

**Comment by DJCrashdummy** [comment]
done: https://f-droid.org/de/packages/in.andres.kandroid/

**Comment by ianme** [comment]
Thanks!
