### ISSUE TITLE
Won't log in to Kanboard version 1.0.40

### ISSUE THREAD

**Issue by mrmurphm** [andresth/Kandroid#5]
**Please, do not create duplicate issues**

### Actual behaviour
When signing into Kanboard Server 1.0.40 (released Feb 24 2017), the error "This server uses a version below 1.0.38. Please Upgrade."

### Expected behaviour
It looks like there might be a server version check that isn't working properly.  

### Steps to reproduce

Install Kanboard 1.0.40.
With Kandroid 0.5, try to log into the 1.0.40 server.  You should get the error message

### Configuration

- Kandroid version:  0.5
- Android/Mod version: 
- Theme (if you use one):
- Device type, name and manufacturer:  Samsung Galaxy S7 Edge
- Kanboard version: 1.0.40

**Comment by mrmurphm** [comment]
I didn't include the full path to my kanboard server.  Rookie mistake.

**Comment by jonasof** [comment]
I think the error message should be more specific, i got the same problem when i login to self signed https server. (Kandroid v0.5.1, Kanboard 1.0.40)

**Comment by Maastodonte** [comment]
Same here on my server with self signed https : "This server uses a version below 1.0.38. Please Upgrade."
I use last kanboard 1.0.41 and Kandroid 0.5.1 from F-Droid.

Don't know if it's a bad error message due to self signed certificate or a bug of version checking.

**Comment by dejj** [comment]
Same problem with Let's Encrypt-signed connection: "This server uses a version below 1.0.38. Please Upgrade."
I use kanboard 1.0.41 and Kandroid 0.5.1 from F-Droid.

**Comment by andresth** [comment]
@Maastodonte, to my knowledge self signed certificates need to be added to the Android certificate storage

**Comment by Maastodonte** [comment]
Tried it but :
1- Android (6.0.1) forced me to configure an unlocking screen on my phone and I don't want that
2- Kandroid still shows the same error message (even with new version 0.5.3)

I think I will give a try to Let's Encrypt for this subdomain.
