### ISSUE TITLE
Support for Android versions earlier than 5

### ISSUE THREAD

**Issue by andresth** [andresth/Kandroid#6]
Check if this is possible

**Comment by dopsi** [comment]
Hi,

I managed to build an APK for KitKat (4.4) by setting `minSdkVersion` and `targetSdkVersion` to 19.
However, the app is stuck in the signin process on two different servers I tried (one has default kanboard authentification, the other one is using remote proxy authentification with HTTP Basic Auth).

I do not have any experience in Android development (a little in Java), but if you have any idea where I should start look to fix this, I'm willing to help.

**Comment by andresth** [comment]
Hi, your help is appreciated.

From my previous test I know that it is enough to change `minSdkVersion`.
I also found some layout issues that needs to be addressed (the menu in the task detail view).

Concerning your login problems, you might want to have a look at [KanboardAPI.java line 895](https://github.com/andresth/Kandroid/blob/master/app/src/main/java/in/andres/kandroid/kanboard/KanboardAPI.java#L895), this is where the `Authenticator` is initialized.
If you can give me more details about the server configurations, I might be able to provide more clues.

**Comment by NevadaKobold** [comment]
Hi! Is it possible that u publish the alternative apk version for Android systems < V.5 here? I really would like to use it on my phone (Android 4.3), but my knowledge about android studio equals zero. 

Kind regards.

**Comment by dopsi** [comment]
The build for the lastest change (6a74e80) is [here](https://dopsi.ch/files/app-debug.apk)

**Comment by andresth** [comment]
I just uploaded the new version here on Github.

**Comment by Jibec** [comment]
thanks for this enhancement, I really appreciate it :) But can you please update the package in f-droid?

**Comment by Jibec** [comment]
I installed the package manually and tried to connect to my server but it crashed.

Here is the log:
> E/ACRA    (18893): ACRA caught a NullPointerException for in.andres.kandroid
> E/ACRA    (18893): java.lang.NullPointerException
> E/ACRA    (18893): 	at in.andres.kandroid.kanboard.KanboardAPI$KanboardAsync.onPostExecute(KanboardAPI.java:240)
> E/ACRA    (18893): 	at in.andres.kandroid.kanboard.KanboardAPI$KanboardAsync.onPostExecute(KanboardAPI.java:105)
> E/ACRA    (18893): 	at android.os.AsyncTask.finish(AsyncTask.java:631)
> E/ACRA    (18893): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
> E/ACRA    (18893): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
> E/ACRA    (18893): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/ACRA    (18893): 	at android.os.Looper.loop(Looper.java:153)
> E/ACRA    (18893): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
> E/ACRA    (18893): 	at java.lang.reflect.Method.invokeNative(Native Method)
> E/ACRA    (18893): 	at java.lang.reflect.Method.invoke(Method.java:511)
> E/ACRA    (18893): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
> E/ACRA    (18893): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
> E/ACRA    (18893): 	at dalvik.system.NativeStart.main(Native Method)
> E/cutils  (18949): to chown(/mnt/shell/emulated/0, 0, 0)
> E/cutils  (18949): to chown(/mnt/shell/emulated/obb, 0, 0)
> E/cutils  (18949): to chown(/storage/emulated/0/Android, 0, 0)
> E/cutils  (18949): to chown(/storage/emulated/0/Android/obb, 0, 0)
> E/cutils  (18962): to chown(/mnt/shell/emulated/0, 0, 0)
> E/cutils  (18962): to chown(/mnt/shell/emulated/obb, 0, 0)
> E/cutils  (18962): to chown(/storage/emulated/0/Android, 0, 0)
> E/cutils  (18962): to chown(/storage/emulated/0/Android/obb, 0, 0)
