### ISSUE TITLE
Successfully connected to the kanboard server, can't get any data

### ISSUE THREAD

**Issue by huangmeng4520** [andresth/Kandroid#8]
**Please, do not create duplicate issues**

### Actual behaviour

Successfully connected to the kanboard server, can't get any data

### Steps to reproducev
![image](https://cloud.githubusercontent.com/assets/8178576/24181185/5e074a14-0ef4-11e7-9e5f-100c038f2634.png)

### Configuration

- Kandroid version:v0.5
- Android/Mod version: 7
- Theme (if you use one):
- Device type, name and manufacturer:huawei
- Kanboard version:1.0.41

**Comment by andresth** [comment]
The Dashboard format changed in Kanboard 1.0.41, that currently breaks my app.
I need to adapt my code to support the new format.

**Comment by huangmeng4520** [comment]
Thank you so much

**Comment by andresth** [comment]
Kandroid 0.5.1 now also works with Kanboard v1.0.41
