### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by EstebanMonge** [andresth/Kandroid#9]
Hello I found that all english strings are in Kandroid/app/src/main/res/values/strings.xml
I create a new directory and file Kandroid/app/src/main/res/values-es/strings.xml, similar to values-de.

I finished all translation, but...

I have two doubts, I can made the pull request, but where in the source code I can include these type of files, I made a grep -r "values" and I don't found the reference.

Spanish language have a lot of tildes and "ñ", for example:
<string name="prompt_password">Contraseña</string>
<string name="action_sign">Iniciar sesión</string>

My question is these string files supports tilde and "ñ" or must be formatted manually, for example: 
<string name="action_sign">Iniciar sesi&oacute;n</string>

If the last one is required, maybe you can configure utf-8.

**Comment by andresth** [comment]
Thanks for your help.

The strings files are already encoded in utf-8, so you should be able to use any character you need. I just forgot to add the xml header.
Please add `<?xml version="1.0" encoding="utf-8"?>` as the first line to your file, like I did in my last commit.

You also don't need to reference the file, Android Studio will add it automatically when you place it in the right directory, which you did.

Could you please try to compile the app to check that your translation works without errors?

**Comment by EstebanMonge** [comment]
Hello I tried to build Kandroid in Android Studio, but I can't, if you want, I can make the commit and you will try to build with spanish translation.

I never used Android Studio or built any Android application.

**Comment by andresth** [comment]
Ok, then please post a pull request. I will test it and merge when everything works.
